version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: tester
      POSTGRES_DB: testdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    command: redis-server --requirepass test
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  redis_data:
